# Generated by Django 3.0.5 on 2020-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entries',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='entries',
            name='id',
        ),
        migrations.AlterField(
            model_name='entries',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
